BASIC python

1.Split this string

In [ ]:
s="Hi there sam!"
s.split()


['Hi', 'there', 'sam!']

2. Use .format() to print the following string.
outpot should be The diameter of Earth is 12742 Kilometers.

In [ ]:
planet ="Earth"
diameter =12742
'The diameter of {} is {} Kilometers.'.format(planet,diameter)

'The diameter of Earth is 12742 Kilometers.'

3. In this nest dictionary grab the word "hello"

In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

**Numpy**

In [ ]:
import numpy as np

4.1 Create an array of 10 zeros?

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.2 Create an array of 10 fives?


In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of all the even integers from 20 to 35

In [ ]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix wirh values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Concatenate a and b

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


**Pandas**

8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
data =[{'a':1, 'b':2},{'a':3, 'b':4},{'a':5, 'b':6}]
df=pd.DataFrame(data)
df

a  b
0  1  2
1  3  4
2  5  6

9. Generate the series of dates from 1st JAN 2023 to 10th FEB 2023

In [ ]:
pd.date_range("01-01-2023","10-02-2023")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

10. Create 2D list to DataFrames

In [ ]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['SI.NO','NAME','AGE'])
print(df)

   SI.NO NAME  AGE
0      1  aaa   22
1      2  bbb   25
2      3  ccc   24
